module.exports = {
    Init            : 'Init',
    GetAllRoom      : 'GetAllRoom',
    JoinRoom        : 'JoinRoom',
    MatchComplete   : 'MatchComplete',
    Match           : 'Match',
    Joined          : 'Joined',
    PlayerMove      : 'PlayerMove',
    BulletMove      : 'BulletMove',
    ItemInit        : 'ItemInit',
    ItemGenerate    : 'ItemGenerate',
    ItemGet         : 'ItemGet',
    Instantiate     : 'Instantiate',
    Destroy         : 'Destroy',
    ShieldUpdate    : 'ShieldUpdate',
    RoundStart      : 'RoundStart',
    RoundUpdate     : 'RoundUpdate',
    SuddenDeathStart: 'SuddenDeathStart',
    Disconnect      : 'Disconnect',
    Refresh         : 'Refresh',
    Error           : 'Error'
};
